myapp/urls.py
from django.urls import path
from . import views
from .views import IngredientesDetailView, IngredientesListView, RecetasDetailView, RecetasListView, TiposListView, TiposDetailView, PortadaListView  

urlpatterns = [
    # Lista ingredientes
    path('', PortadaListView.as_view(), name = 'id_port'),
    path('ingredientes/', IngredientesListView.as_view()),
    # Detalle de los ingredientes
    path('ingredientes/<int:pk>', IngredientesDetailView.as_view(), name='id_ing'),
    path('tipos/', TiposListView.as_view()),
    path('tipos/<int:pk>', TiposDetailView.as_view(), name = 'id_tip'),
    path('recetas/', RecetasListView.as_view()),
    path('recetas/<int:pk>', RecetasDetailView.as_view(), name = 'id_re'),
    path('login/', views.login_request, name= "login"),
    path('registro/', views.register_request, name= "registro"),
#    path('añadirReceta/', views.RecetaForm.as_view(), name="añadirReceta"),
    path('añadirReceta/', views.CantidadCreateView.as_view(), name="añadirReceta"),
    path('logout/', views.logout_request, name= "logout"),
]

recipesstore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
]

myapp/models.py
from django.db import models

class TipoReceta(models.Model):
    tipo = models.CharField(max_length=50)
    def __str__(self):
        return self.tipo

class DuracionReceta(models.Model):
    duracion = models.CharField(max_length=50)
    def __str__(self):
        return self.duracion

class Receta(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=10000)
    tiempo = models.IntegerField(default = 0)
    tipo = models.ForeignKey(TipoReceta, on_delete=models.CASCADE, default=None)
    duracion = models.ForeignKey(DuracionReceta, on_delete=models.CASCADE, default=None)
    def __str__(self):
        return self.nombre

# Creacion de la clase Ingrediente
class Ingrediente(models.Model):
    nombre = models.CharField(max_length=100)
    calorias = models.IntegerField(default = 0)
    def __str__(self):
        return self.nombre

class Cantidad(models.Model):
    cantidad = models.FloatField(default=0)
    unidad = models.CharField(max_length=40)
    receta = models.ForeignKey(Receta, on_delete=models.CASCADE, default = None)
    ingrediente = models.ForeignKey(Ingrediente, on_delete=models.CASCADE, default = None)
    def __str__(self):
        return self.unidad

class Usuario(models.Model):
    nombre = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    password = models.CharField(max_length=30)
    def __str__(self):
        return self.nombre

myapp/forms.py
from django import forms
from django.forms import ModelForm
from .models import Usuario, Receta
#---------
from .models import Ingrediente, Cantidad
from betterforms.multiform import MultiModelForm
#---------
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class newUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2", "groups")
    
    def save(self, commit = True):
        user = super(newUserForm, self).save(commit = False)
        user.email = self.cleaned_data['email']
        user.group = self.cleaned_data['groups']
        if commit: 
            user.save()
        return user


class RecetaModelForm(ModelForm):
    class Meta:
        model = Receta
        fields = '__all__'
        
"""class IngredienteModelForm(ModelForm):
    class Meta:
        model = Ingrediente
        fields = '__all__'"""
        
class CantidadModelForm(ModelForm):
    class Meta:
        model = Cantidad
        fields = ['ingrediente', 'cantidad', 'unidad']
        
class CantidadRecetaIngredienteModelForm(MultiModelForm):
    form_classes = {
        'receta': RecetaModelForm,
        'cantidad': CantidadModelForm,
    }

myapp/views.py
from django.shortcuts import get_list_or_404, get_object_or_404
from .models import Receta, Ingrediente, Cantidad, TipoReceta, Usuario
from django.http import HttpResponse
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.db.models.query import QuerySet
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from .forms import newUserForm, CantidadRecetaIngredienteModelForm
from django.template import RequestContext
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
# Create your views here.

# Vista para ver todos los ingredientes

class IngredientesListView(ListView):
    model = Ingrediente
    querySet = Ingrediente.objects.all()
    ordering = ('nombre',)
    template_name = 'listaIngredientes.html'

class IngredientesDetailView(DetailView):
    model = Ingrediente
    template_name = 'detalleIngrediente.html'
    
class TiposListView(ListView):
    model = TipoReceta
    querySet = TipoReceta.objects.all()
    template_name = 'listaTipos.html'
    
class TiposDetailView(DetailView):
    model = TipoReceta
    template_name = 'detalleTipos.html'

class RecetasListView(ListView):
    model = Receta
    querySet = Receta.objects.all()
    ordering = ('nombre',)
    template_name = 'listarecetas.html'

class RecetasDetailView(DetailView):
    model = Receta
    template_name = 'detallereceta.html'

class PortadaListView(ListView):
    model = TipoReceta
    QuerySet = TipoReceta.objects.all()
    template_name = 'portada.html'

def register_request(request):
    if request.method == "POST":
        form = newUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.groups.add(request.POST.get("groups"))
            login(request, user)
            messages.success(request, "Registro correcto")
            return redirect("/myapp/")
        messages.error(request, "Algunos campos del registro son erróneos")
    form = newUserForm()
    return render(request=request, template_name = "registro.html", context ={"register_form": form})

def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data= request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username = username, password = password)
            if user is not None:
                login(request, user)
                messages.info(request, f"Estas logeado como {username}")
                return redirect("/myapp/")
            else:
               messages.error(request, "Usuario o contraseña incorrecta")  
        else:
            messages.error(request, "Usuario o contraseña incorrecta")
    form = AuthenticationForm()
    return render(request=request, template_name = "login.html", context ={"login_form": form})

def logout_request(request):
    logout(request)
    return redirect("/myapp/")
  

class CantidadCreateView(CreateView):
    form_class = CantidadRecetaIngredienteModelForm
    template_name = 'añadirReceta.html'
    
    def form_valid(self, form):
        receta = form['receta'].save()
        cantidad = form['cantidad'].save(commit=False)
        cantidad.receta = receta
        cantidad.save()
        success_url = reverse_lazy('id_port')
        return redirect("/myapp/")

myapp/templates/añadirReceta.html
{% extends "index.html" %}
{%load crispy_forms_tags%}
{% load static %}
{% block title %}Añadir receta{% endblock %}
{% block h1 %}Añadir receta{% endblock %}

{% block content %}
<h2>Añadir nueva receta</h2>
<form method="POST">
    {% csrf_token %}
    {{ form | crispy }}
</br>
<!--    {{ form.ingrediente | crispy }} -->
    <input type="submit" value="Añadir receta" id="btmAñadir"/>
</form>
{% endblock %}




myapp/templates/detalleIngrediente.html
{% extends "index.html" %}
{% load static %}
{% block title %}Ingrediente{% endblock %}
{% block h1 %}Detalle Ingrediente{% endblock %}
{% block imagen %}
    <img src="{% static "" %}images/{{ object.nombre|cut:" " }}.png" alt="{{ object.nombre }}" class="center" width="200">
{% endblock %}
{% block content %}
    <h2>{{ object.nombre }}</h2>
    <ul>
        <li><span>Calorias:</span> {{ object.calorias }} Kcal/100g</li>
    </ul>
    <h2>Recetas asociadas</h2>
    <ul>
        {% for receta in object.cantidad_set.all %}
            <li><a href="{%url 'id_re' receta.receta.id%}">{{ receta.receta.nombre }}</a></li>
    
        {% endfor %}
    </ul>
{% endblock %}

myapp/templates/detalleTipos.html
{% extends "index.html" %}
{% block title %}Tipos{% endblock %}
{% block h1 %}Detalle Tipos{% endblock %}
{% block content %}
    <h2>{{ object.tipo }}</h2>
    <h2>Recetas asociadas</h2>
    <ul>
        {% for receta in object.receta_set.all %}
            <li><a href="{%url 'id_re' receta.id%}">{{ receta.nombre }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

myapp/templates/detallereceta.html
{% extends "index.html" %}
{% load static %}s
{% block title %}Receta{% endblock %}
{% block h1 %}Detalle Receta{% endblock %}

{% block imagen %}
    <img src="{% static "" %}images/{{ object.nombre|cut:" " }}.png" alt="{{ object.nombre }}" class="center" width="200">
    
{% endblock %}

{% block content %}
    <h2>{{ object.nombre }}</h2>
    <h2>Ingredientes</h2>
    <ul>
        {% for cantidad in object.cantidad_set.all %}
    
            <li><a href="{%url 'id_ing' cantidad.ingrediente.id%}">{{ cantidad.ingrediente.nombre }}</a> : {{ cantidad.cantidad }} {{ cantidad.unidad }}</li>
    
        {% endfor %}
    </ul>
    <ul>
        <li><span>Tipo:</span> {{ object.tipo.tipo }}</li>
        <li><span>Duración:</span> {{ object.duracion.duracion}}</li>
        <li><span>Tiempo:</span> {{ object.tiempo }} min</li>
        <li><span>Preparación:</span><p> {{ object.descripcion }}</p></li>
    </ul>
{% endblock %}
{% block app %}
    <h2> {$ counter $} me gusta</h2>
    {% if user.is_authenticated %}
        <button v-on:click="counter++">Me gusta</button>
        <button v-on:click="counter--">No me gusta</button>
    {% endif %}
{% endblock %}

myapp/templates/index.html
{% load static %}
<!DOCTYPE HTML>
<html>
  <head>
    <title>{% block title %}{% endblock%}</title>
    <meta name="description" content="website description"/>
    <meta name="keywords" content="website keywords, website keywords"/>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <meta mame ="viewport" content"width-device-width">
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link rel="icon" href="{%static 'images/logo.png'%}" type="image/png"/>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
  </head>

  <body>
    <main>
      <header>
        <div id="logo">
          <div id="logo_text">
            <!-- class="logo_colour", allows you to change the colour of the text -->
            <h1><a href="/myapp/">Recetas de la abuela</a></h1>
            <h2><b>Rico, rico y para toda la familia</b></h2>
          </div>
          <div class="usuario">
          {% if user.is_authenticated %}
              <h3>Hola, {{ user.username }}</h3>
          {% endif %}
          </div>
        </div>
        <div id="menubar">
          <ul id="menu">
            <!-- put class="selected" in the li tag for the selected page - to highlight which page you're on -->
            <li><a href="/myapp/">Home</a></li>
            <li><a href="/myapp/recetas/">Recetas</a></li>
            <li><a href="/myapp/tipos/">Tipos de Receta</a></li>
            <li><a href="/myapp/ingredientes/">Ingredientes</a></li>
            {% if user.is_authenticated %}
                <li><a href="/myapp/logout/">Cerrar sesión</a></li>
            {% else %}
                <li><a href="/myapp/login/">Iniciar sesión</a></li>
            {% endif %}
          </ul>
        </div>
      </header>
    </main>
      <div id="site_content">
        <div class="sidebar">
          {% block boton %} {% endblock %}
          <!-- insert your sidebar items here -->
          {% block imagen %}{% endblock %}
        </div>
        <div id="content">
          {% block content %}{% endblock %}
          <div id="app">
              {% block app %}{% endblock %}
          </div>
        </div>
      </div>
      <script type="text/javascript">
          var app = new Vue({
              el: '#app',
              delimiters:['{$','$}'],
              data:{
                  counter: '0'
              },
              mounted(){
                  if (localStorage.counter){
                      this.counter = localStorage.counter;
                  }
              },
              watch: {
                  counter(newCounter){
                      localStorage.counter = newCounter;
                  }
              }
          });
      </script>
  </body>
</html>

myapp/templates/listaIngredientes.html
{% extends "index.html" %}
{% block title %}Listado_Ingredientes{% endblock %}
{% block h1 %}Listado de Ingredientes{% endblock %}
{% block content %}
<h2>Lista de Ingredientes</h2>
<ul>
{% for ingrediente in object_list %}
    <li><a href="{%url 'id_ing' ingrediente.id%}">{{ ingrediente.nombre }}</a></li>
{% endfor %}
</ul>
{% endblock %}

myapp/templates/listaTipos.html
{% extends "index.html" %}
{% block title %}Listado_Tipos{% endblock %}
{% block h1 %}Listado de tipos{% endblock %}
{% block content %}
<h2>Lista de Tipos de Recetas</h2>
<ul>
    {% for tipo in object_list %}
    <li><a href="{% url 'id_tip' tipo.id %}">{{tipo.tipo}}</a></li>
    {% endfor %}
</ul>
{% endblock %}

myapp/templates/listarecetas.html
{% extends "index.html" %}
{% load static %}
{% load auth_extras %}

{% block title %}Listado_Recetas{% endblock %}
{% block h1 %}Listado de Recetas{% endblock %}


{% block content %}
<h2>Lista de Recetas</h2>
<ul>
{% for receta in object_list %}
    <li><a href="{%url 'id_re' receta.id%}">{{ receta.nombre }}</a></li>
{% endfor %}
</ul>
{% endblock %}
{% block boton %}
{% if request.user.is_authenticated %}
    {% if request.user|has_group:"Cocinero" %}
        <a href="/myapp/añadirReceta/"><input type="button" value="Añadir receta" class="botonAñadirReceta"></a>
    {% else %}
        <input type="button" value="Añadir receta" class="botonAñadirReceta" disabled>
    {% endif %}
{% else %}
    <input type="button" value="Añadir receta" class="botonAñadirReceta" disabled>
{% endif %}
{% endblock %}

myapp/templates/login.html
{% extends "index.html" %}
{%load crispy_forms_tags%}
{% load static %}
{% block title %}InicioSesión{% endblock %}
{% block h1 %}Inicia sesión{% endblock %}

{% block content %}
<h2>Inicio de sesión</h2>
<form method="POST">
    {% csrf_token %}
    {{ login_form | crispy }}
</br>
<input type="submit" value="Iniciar sesión" id="button2"/>
</form>
</br>
{% for message in messages %}
<div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
</div>
{% endfor %}
</br>
<p>Aun no tienes cuenta? Registrate Gratis</p>
<form action="/myapp/registro/"><input type="submit" value="Registrar" id="button"/></form>

{% endblock %}

myapp/templates/portada.html
{% extends "index.html" %}
{% load static %}
{% block title %}Portada{% endblock %}
{% block h1 %}Portada{% endblock %}

{% block imagen %}
    <img src="{% static '/images/abuela.png' %}" alt="abuela" class="center" width="200">
{% endblock %}

{% block content %}
<h2>Portada</h2>
{% for tipo in object_list %}
<p>{{ tipo.tipo }}</p>
    <ul>
    {% for receta in tipo.receta_set.all %}
        {% if forloop.first %}
            <li><a href="{%url 'id_re' receta.id%}">{{ receta.nombre }}</a></li>
        {% endif %}
    {% endfor %}
    </ul>
{% endfor %}
{% endblock %}

myapp/templates/registro.html
{% extends "index.html" %}
{%load crispy_forms_tags%}
{% load static %}
{% block title %}Registro{% endblock %}
{% block h1 %}Registro{% endblock %}

{% block content %}
<h2>Registro</h2>
<form method="POST">
    {% csrf_token %}
    {{ register_form | crispy }}
</br>
<input type="submit" value="Registrar" id="button"/>
</form>
</br>
{% for message in messages %}
<div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
</div>
{% endfor %}
{% endblock %}